insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('701-63-7130', 'Dibbert LLC', 'Otis Jestico', 2010, 48, 1);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('307-73-9274', 'Larson Group', 'Quinton Enders', 1986, 9, 0);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('445-38-6718', 'Ruecker Inc', 'Sissie Yarrell', 1992, 21, 0);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('438-88-6559', 'Collins, Baumbach and Davis', 'Iggie Kleinschmidt', 1988, 11, 1);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('292-73-7586', 'Reichel LLC', 'Magdalena Mulliner', 2004, 38, 0);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('706-06-4189', 'Oberbrunner-Ward', 'Vickie Chason', 1992, 47, 1);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('828-56-8616', 'Schowalter, Stehr and Terry', 'Axel Storrier', 2002, 24, 0);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('830-96-7728', 'Parisian Inc', 'Matthias Birtwell', 2001, 57, 0);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('823-22-4615', 'Keebler and Sons', 'Leonie Bedle', 1993, 66, 0);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('442-30-1729', 'Russel, D''Amore and Lebsack', 'Lyndsey Sweetlove', 1993, 52, 0);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('826-21-3762', 'Fadel-Muller', 'Jeramie Olekhov', 2010, 31, 0);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('268-57-3863', 'Simonis-Bogisich', 'Grethel Penswick', 2004, 65, 0);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('293-32-2418', 'Littel, Terry and Emard', 'Carly Milroy', 2003, 8, 1);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('287-69-8628', 'Franecki and Sons', 'Birgitta Palliser', 2000, 69, 0);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('673-18-2317', 'Tremblay and Sons', 'Lonnie McKearnen', 2002, 99, 0);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('273-62-9748', 'Runolfsdottir LLC', 'Kristian Ridges', 1994, 55, 0);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('476-59-9623', 'Berge Group', 'Lissie Brandsma', 2011, 55, 1);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('724-26-9507', 'Grant-Harvey', 'Darrick Cadamy', 1994, 76, 1);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('184-92-0110', 'Turner, Stark and Rogahn', 'Alison Bills', 2011, 85, 1);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('733-07-0701', 'Weissnat-Sawayn', 'Maddie Kearton', 2007, 33, 1);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('200-20-2090', 'Olson-Heathcote', 'Eveline Loader', 2011, 61, 0);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('606-69-1009', 'Renner Group', 'Hendrick Elleyne', 2003, 5, 1);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('412-29-3940', 'Bogisich Inc', 'Kelcie Danielovitch', 1997, 8, 1);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('609-93-0030', 'Wiegand and Sons', 'Mateo Pimlock', 2008, 55, 0);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('295-19-5522', 'Lueilwitz LLC', 'Murial Orsi', 2010, 44, 1);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('761-82-0657', 'Okuneva, Mante and Auer', 'Jolynn Swinfon', 1998, 82, 0);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('526-38-4296', 'McGlynn, Gusikowski and Halvorson', 'Edlin Kalker', 1993, 21, 1);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('535-20-5792', 'Rodriguez LLC', 'Josie Feast', 1989, 4, 1);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('716-04-1672', 'Luettgen, Osinski and Senger', 'Solomon MacFall', 2007, 91, 0);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('263-10-4263', 'Kessler, Gislason and Mohr', 'Bary Heikkinen', 2003, 55, 1);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('884-80-8204', 'Crist, Padberg and Wiegand', 'Calhoun Strand', 1996, 72, 1);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('249-86-5442', 'Reinger and Sons', 'Archie Foden', 2004, 37, 0);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('403-92-1519', 'Deckow, Skiles and Klocko', 'Torrence Michin', 1993, 83, 1);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('346-28-7986', 'Kling LLC', 'Gardy De Castri', 2001, 31, 1);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('636-45-2174', 'Wisozk-Lowe', 'Cherey Devey', 2006, 67, 0);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('472-28-2243', 'Becker, Bradtke and Koepp', 'Dodi Destouche', 2011, 14, 1);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('263-42-2221', 'Mayert Group', 'Miller Symers', 2002, 64, 0);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('348-70-8654', 'Lesch Inc', 'Shela Terlinden', 1995, 35, 1);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('382-02-2043', 'Schmitt LLC', 'Donelle Rendall', 1995, 90, 1);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('639-17-3819', 'Witting, Gutmann and Hilpert', 'Northrup McKevin', 1995, 30, 0);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('663-40-3811', 'Kulas-Bins', 'Kathlin Tallboy', 1997, 85, 1);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('467-28-7746', 'Konopelski-D''Amore', 'Matilda Defries', 2001, 69, 0);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('870-70-9054', 'Goyette, Morissette and Haag', 'Allin Tolliday', 1997, 49, 0);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('858-58-5405', 'Friesen, Botsford and Franecki', 'Lynde Dawnay', 2002, 67, 0);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('297-09-5521', 'Wisozk Group', 'Humphrey Fewtrell', 1986, 82, 0);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('880-03-4791', 'Moen, Brekke and Stanton', 'Erda Welfare', 1992, 89, 1);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('275-91-0837', 'Kiehn-Hirthe', 'Lil Menis', 1986, 5, 1);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('243-34-6456', 'Larson, Wolf and Lind', 'Merci Churchlow', 1997, 79, 1);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('793-69-4999', 'Gleichner and Sons', 'Kellby Elphinston', 1987, 85, 0);
insert into Ksiazka (ISBN, Tytul, Autor, Rok_Wydania, Cena, Wypozyczona_Ostatni_Miesiac) values ('784-69-2199', 'Fisher-Kemmer', 'Eugene Peachey', 2012, 52, 0);
